<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Corelle</name>
   <tag></tag>
   <elementGuidId>30138e9b-c305-453f-99df-4e0a77ae54d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2050']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2050 > a.item-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afd1d6bc-abe2-4e5e-9df7-3d575537647e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/brand/corelle/</value>
      <webElementGuid>1dcc089d-10a8-4bc3-a285-07e0cbef28f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>c7e1436a-e37a-49cb-8d3e-4e39364eee63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corelle</value>
      <webElementGuid>fd0cebcf-4ebf-4e5f-8ca4-00bd345de506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-all-departments-1&quot;)/li[@id=&quot;menu-item-2035&quot;]/div[@class=&quot;nav-sublist-dropdown&quot;]/div[@class=&quot;container&quot;]/ul[1]/li[@id=&quot;menu-item-2050&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>6eebcfdc-e103-48eb-8d11-169d77125ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0893fb6d-b37e-47cd-8770-0bb3a01c9336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/brand/corelle/</value>
      <webElementGuid>3fbd9d94-4051-4aa8-bea1-1a20644979a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>ba14d985-83cf-449d-bd70-e646d5cea300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corelle</value>
      <webElementGuid>1a78208f-c95f-47ee-9562-fc04d8bd86de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-all-departments-1&quot;)/li[@id=&quot;menu-item-2035&quot;]/div[@class=&quot;nav-sublist-dropdown&quot;]/div[@class=&quot;container&quot;]/ul[1]/li[@id=&quot;menu-item-2050&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>fe003070-800c-4f5e-a6d8-9a517512a4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2050']/a</value>
      <webElementGuid>e7a6e64f-f22b-4aa4-bb51-1f8c766f0d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Corelle')]</value>
      <webElementGuid>66d435d4-74d1-41c8-b5e0-b79741e187fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by Brands'])[1]/following::a[1]</value>
      <webElementGuid>ba3e3ef7-054c-4db1-b8f2-117e16558bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All departments'])[1]/following::a[2]</value>
      <webElementGuid>1fba6d03-2fb1-4bf0-b49e-56624ad02de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corningware'])[1]/preceding::a[1]</value>
      <webElementGuid>3dd00aeb-7a31-4f16-9df6-b7182319ba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F. Herder'])[1]/preceding::a[2]</value>
      <webElementGuid>5aa0a3b1-ddfe-4403-87df-f38baaee331f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corelle']/parent::*</value>
      <webElementGuid>8a6efc4e-7238-4db1-a636-a4da5d3ec9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kitchenplaza.com.my/brand/corelle/')]</value>
      <webElementGuid>b100043d-d63a-4059-885c-ca60c1a2e83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/ul/li/a</value>
      <webElementGuid>9e1fbc5c-b699-422d-9139-3cb868e769e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kitchenplaza.com.my/brand/corelle/' and (text() = 'Corelle' or . = 'Corelle')]</value>
      <webElementGuid>216442f7-c0ed-42ae-bfff-c9bd1b96d336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
