<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cookware</name>
   <tag></tag>
   <elementGuidId>17ee738b-29f5-4386-8b8a-5ea8706f8494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3027']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3027 > a.item-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e0f4bc0-38c9-4a4d-95ea-1e8387f4bee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/product-category/cookware/</value>
      <webElementGuid>0ddb5e61-26b0-4c84-ad03-69ae50780374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>f4373f3d-5185-4b95-9f71-26356c5d5ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cookware</value>
      <webElementGuid>a6f49b5c-dacf-4e19-9e9a-0b83cfde687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-all-departments-1&quot;)/li[@id=&quot;menu-item-3027&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>c2895e42-7c03-4a16-a612-644c63aebd64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3027']/a</value>
      <webElementGuid>ba025b43-504b-4a0c-b94d-60ac78aa2457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cookware')]</value>
      <webElementGuid>25c60e76-ec95-4da0-a0bc-b07d3472ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utensil &amp; Cutlery'])[1]/following::a[1]</value>
      <webElementGuid>8139535a-ebaf-47b5-ada9-787c09251ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serveware'])[1]/following::a[2]</value>
      <webElementGuid>33baaa60-8712-458b-97b6-8239f5b3c4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enameled Cast Iron'])[1]/preceding::a[1]</value>
      <webElementGuid>8945d336-4653-4fa4-8b7e-df3cdf905bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Glass Ceramic Pyroceram'])[1]/preceding::a[2]</value>
      <webElementGuid>8f351f00-5e7d-4b3f-abf6-e9f1e8e4f8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cookware']/parent::*</value>
      <webElementGuid>cc9fb9fd-55ad-436d-ad46-555f90ee7832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kitchenplaza.com.my/product-category/cookware/')]</value>
      <webElementGuid>6b077905-bf11-4c8c-8fe5-d244686ff2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>650bd5a4-de3b-497b-81c9-be20e4c9c285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kitchenplaza.com.my/product-category/cookware/' and (text() = 'Cookware' or . = 'Cookware')]</value>
      <webElementGuid>92fc51f3-0d95-4bcb-bd8f-d8fd68f0c5c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
