<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tableware</name>
   <tag></tag>
   <elementGuidId>c2b88bdf-8c57-4f8c-82de-8b9ecdc08f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3018']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3018 > a.item-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9184a70-6d30-4786-a6d8-e2fbe6361360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/product-category/tableware/</value>
      <webElementGuid>d5caad58-b782-4370-a21a-b40ce0d031e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>33d054b4-0921-496e-ab94-3c7fdd9523e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tableware</value>
      <webElementGuid>212df8d4-ca3c-46b7-a6ac-3fa122e202ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-all-departments-1&quot;)/li[@id=&quot;menu-item-3018&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>28dcaceb-97c7-4049-b78e-0330176a7720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3018']/a</value>
      <webElementGuid>df9fe0d7-e5d4-462e-9bf1-3d054831f0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tableware')]</value>
      <webElementGuid>7c1cc05f-3709-438a-a842-81e515647efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visions'])[1]/following::a[1]</value>
      <webElementGuid>85c72fa4-84cc-490d-a24b-16d2a29ba17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Victorinox'])[1]/following::a[2]</value>
      <webElementGuid>722fad54-f7ec-463e-b850-85cfdbd78ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dinner Set'])[1]/preceding::a[1]</value>
      <webElementGuid>2db26850-c34e-4d34-8d9b-3c84b4ccbdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bowls'])[1]/preceding::a[2]</value>
      <webElementGuid>d24ce4a9-ce60-4c40-9b33-d6e47d2414e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tableware']/parent::*</value>
      <webElementGuid>562f47a6-b173-4acb-af20-ec3c9fd98989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kitchenplaza.com.my/product-category/tableware/')]</value>
      <webElementGuid>15c7384b-31d9-4959-b0a5-95d1e51a04f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>60bc9452-8b20-49a9-b6fa-ac18c1149d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kitchenplaza.com.my/product-category/tableware/' and (text() = 'Tableware' or . = 'Tableware')]</value>
      <webElementGuid>034b2c52-38dd-4e77-8f98-dc89751c64c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
