<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3c0857b6-cef3-4fc8-b23b-1d1a4ccb78cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-028cefb51a7102d23']/div[14]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-visible > div.category-grid.category-image-circle.slide-item.text-color-dark.valign-center.style-classic.content-under.product-category.product > a > img[alt=&quot;Portmeirion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4fc08385-2558-4e81-b1f3-d80cc2a5efdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>da783fb2-70c7-447c-97fd-6d0f808e6334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1.jpg.webp</value>
      <webElementGuid>d7b12253-c7d9-41a0-8457-72edc2b8179e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Portmeirion</value>
      <webElementGuid>0584a0ee-5e6c-4536-b26f-828432b60686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>9612faca-3c08-48b5-bad7-e92e53519a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>a3bad4f6-a29e-4a35-90e5-706b002c5cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1.jpg.webp 300w, https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1-150x150.jpg.webp 150w, https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1-1x1.jpg.webp 1w, https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1-10x10.jpg.webp 10w, https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1-100x100.jpg.webp 100w</value>
      <webElementGuid>34fb786b-65df-4760-930b-d2362efe12b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>efdbfe4e-a9f7-4267-90e2-95323139011c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-028cefb51a7102d23&quot;)/div[@class=&quot;swiper-slide swiper-slide-visible&quot;]/div[@class=&quot;category-grid category-image-circle slide-item text-color-dark valign-center style-classic content-under product-category product&quot;]/a[1]/img[1]</value>
      <webElementGuid>b33c48a9-c7ef-4856-a3f4-3af4e4bfc387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-028cefb51a7102d23']/div[14]/div/a/img</value>
      <webElementGuid>35fbd067-9596-4b07-bee7-476c7219f487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Portmeirion'])[2]</value>
      <webElementGuid>26566db3-4506-47ef-bcaa-d61a58d2b5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/a/img</value>
      <webElementGuid>9f6212f8-bcf5-48bb-9946-316c9d6c7692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kitchenplaza.com.my/wp-content/uploads/2022/08/Portmeirion-300x300-1.jpg.webp' and @alt = 'Portmeirion']</value>
      <webElementGuid>9655cc52-5457-4a08-9ae5-29b94b778d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
